### ISSUE TITLE
Variant Pre-selection

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#1013]
The variants `makeSelections` method needs to be implemented to take a group of options and pre-select variants based on them. Currently without any options the method will pre-select the first available option in each selection.

```
options = {color: ['Blue'], size: ['L']};
```

Currently the object will need to be keyed by the selection field in order to properly work. Each option should support providing multiple values.

**Comment by chrisFrazier77** [comment]
need to explore adding the ability to setVariants using the event manager. This would allow a site to tie into searchspring.on('selectVariant') to update all results (or by specific profile) with selected variants

**Comment by korgon** [comment]
Released in v0.54.0
