### ISSUE TITLE
Documentation on `result.display`

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#1098]
The SearchResultStore recently had a release with the variants that included a new property `display`. Together with the `mask` property `display` is used as a way to "overlay" various data points without altering the store altogether. This functionality is used in order to allow for selection of variants to alter result data (eg. `mappings.core.price`) displayed by components.

Documentation needs to be added to the Snap docs to describe how this works and when and where it should be utilized.

Additionally, it seems we are missing some documentation on the `result.variants.update` function and any other methods that need to be utilized to update variant pricing or other details.

**Comment by chrisFrazier77** [comment]
https://github.com/searchspring/snap-1.0/pull/23

**Comment by korgon** [comment]
Merged into fork `develop` branch.
