### ISSUE TITLE
RecommendationEmail Component

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#1156]
Need a component for Snap Templates to handle email recommendations. Currently the simple wrapper is defined via a custom component, but this needs to be moved to an actual component for templates functionality.

See scaffold and library for examples:
https://github.com/searchspring/snapfu-scaffold-preact-email/blob/production/src/components/Recommendations/Email.jsx
https://github.com/searchspring/snapfu-library/blob/main/preact/components/recommendation/email/default/Email.jsx

**Comment by dkonieczek** [comment]
Awaiting other team to resolve smc bug blocking an email recommendation profiles from being created (needed for storybook)

**Comment by korgon** [comment]
Merged into `templates`.
