### ISSUE TITLE
ss-name and ss-treepath

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#1205]
For the `ss-name` and `ss-treepath` attributes, is it possible to ensure these attributes are placed on elements in the DOM _only_ when we are in development mode? These attributes are mostly there to help with identification of components during development and support for Snap Templates.

However, if this is the functionality, If someone were to use these attributes for building style selectors during development, would this cause issues when these selectors disappear on the live site?

**Comment by chrisFrazier77** [comment]
https://github.com/searchspring/snap-1.0/pull/24

**Comment by korgon** [comment]
Merged into `develop` of 1.0 fork.
