### ISSUE TITLE
Autocomplete Component Testing

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#177]
The current tests are a bit lacking and do not test any props. Unit tests for components should have mock data and test each prop and various combinations of props to ensure that they are working as expected.

**Comment by korgon** [comment]
Seeing failures due to this specific test (not the proposed changes):
![image](https://user-images.githubusercontent.com/5060400/152062551-945ffea3-3632-4591-b340-69c752e90b89.png)

**Comment by chrisFrazier77** [comment]
Thats odd I didnt even change that test..
