### ISSUE TITLE
Branch Preview Window

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#346]
Noticed this while testing on a site. The close icon in the branching window could use styling to prevent if from getting too big. In this case, the svg was inheriting styles from the site's stylesheet (such as `position: absolute, width: 100%`, etc). It won't happen all the time, but maybe add overrides to prevent this.

**Comment by korgon** [comment]
Added some additional styling to help preserve display in: https://github.com/searchspring/snap/pull/466

**Comment by korgon** [comment]
Thanks Adria - I saw this as well and it should be corrected on next release!
