### ISSUE TITLE
Carousel `loop` with low product count

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#361]
`Carousel` component duplicates results when loop is enabled. Additionally if only 1 product is displayed, it doesn’t take the full width of a slide.

It has been found that when the `loop` prop is enabled and the number of results is less than the `slidesPerView` that has been set, Swiper will fill the carousel by repeating the results until there are enough to loop through. This presents a problem with recommendation template re-use.

Recommendation profiles typically utilize the same template, where let's say `loop` is enabled and `slidesPerView` is set to 5; not all profiles will have > 5 results. For example suppose there is a profile for 'last viewed', it shows the last products viewed. After viewing a single product it would show only that one result repeated 5 times.

A possible solution would to modify the Recommendation component to auto-disable `loop` if it is enabled when results are lower than `slidesPerView`.

**Comment by dkonieczek** [comment]
This change will be included with https://github.com/searchspring/snap/pull/342
