### ISSUE TITLE
Mobile iOS body-scroll-locking for slideout menu

### ISSUE THREAD

**Issue by R2B1** [searchspring/snap#363]
The current method of preventing scrolling of the page body with the slideout menu open is to add an `overflow: hidden;` style to the `body` tag, which works well on most browsers but not so much on mobile iOS. We need a more robust solution like the one implemented in the [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock) package that works in all browsers and doesn't limit functionality.

**Comment by chrisFrazier77** [comment]
After chatting with Ryan on this one, he mentioned it was really only an issue on reef.com (so far) and he saw it on safari on iphone. 

I tested on my actual phone on the demo store, as well as pulled down reef, uninstalled body-scroll-lock, and tested on my phone again on chrome and safari. And I cant seem to find any unexpected behavior with the scrolling in the slideout. Not sure what I'm missing or maybe its just not reproducible on my phone? Iphone 11 Pro on v14.2

Here is a screen recording from my phone, any long pauses you see is me trying to scroll off to the left in the background, which doesn't do anything as I would have expected. 
https://user-images.githubusercontent.com/22894994/161303892-d73b11c6-f23c-460c-82da-8a277d50d3a8.MP4
