### ISSUE TITLE
Trending Searches

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#418]
Displaying Trending Searches in the Autocomplete works well and I think it's a great feature. However, I was wondering if it would be possible to keep a list of trending terms and suggested terms in the Autocomplete? I did this once for a site, but the Autocomplete became a custom component at that point, so I'm wondering if there is a way for us to tie this into the Snap component? I think having a separate loop under the suggested terms would be good enough, still on the left side of Autocomplete (in desktop view).

**Comment by korgon** [comment]
This has been possible for awhile now - just forgot to close this issue.
