### ISSUE TITLE
Typing: snap-preact-components

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#441]
Enable Typescript `strict` mode.

**Comment by chrisFrazier77** [comment]
this is done || really close to done, but needs snap-preact to be typed first.

**Comment by korgon** [comment]
I was thinking about this just now - and this should not be the case. Since this package is a dependency of `snap-preact` it should not depend on it... It could be that this was done prior to the change in dependency (used to be the other way around).

About to merge in `snap-preact` typing into `develop` anyhow - but I don't think it was really a blocker anymore :)
