### ISSUE TITLE
Carousel and autoAdjustSlides prop

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#464]
Currently this prop is set to `true` by default:
https://github.com/searchspring/snap/blob/main/packages/snap-preact-components/src/components/Molecules/Carousel/Carousel.tsx#L152

I feel that it should be `false`. When it is enabled, it often distorts the design. I had a design when the slidesPerView was four, but with this setting and there being only two items, it made the slides very wide (which I understand is the point), but it clashed with the design. I feel in most cases, people are going to want consistency in the slide width.

It also took me a little bit to figure out where this was coming from (if it was with the Snap component or Swiper).

**Comment by adriamurphy** [comment]
Somewhat related, I could not find this prop in the docs for `Carousel` (`centerInsufficientSlides`) so I was not sure how my slider was being centered:
https://github.com/searchspring/snap/blob/main/packages/snap-preact-components/src/components/Molecules/Carousel/Carousel.tsx#L242

**Comment by korgon** [comment]
@adriamurphy Is this still an issue for you?

**Comment by adriamurphy** [comment]
@korgon Sorry I didn't see your message here. It looks like the defaults for `centerInsufficientSlides` and `autoAdjustSlides` are set to `true` by default. At the very least, I feel that `autoAdjustSlides` should not be `true` by default as this can distort the design in a bad way while centering is just... centering the slides.

**Comment by korgon** [comment]
We will look into the feasibility of making this change, however, we may be unable to modify it due to backwards compatibility concerns.

**Comment by korgon** [comment]
This will have to remain enabled by default, as there is no easy way to good way to change it without introducing breaking changes.
