### ISSUE TITLE
Failing Lighthouse test

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#478]
![Screen Shot 2022-05-02 at 4 28 37 PM](https://user-images.githubusercontent.com/13966707/166322345-88934951-8668-4310-8617-8b5e243d9c1e.png)

Context: https://searchspring.slack.com/archives/C028X3E38BB/p1651511855122819?thread_ts=1651508474.067749&cid=C028X3E38BB

**Comment by dkonieczek** [comment]
Tried numerous things here but couldn't resolve. Not urgent as the implementation is just skipping the lighthouse tests in the meanwhile.

**Comment by korgon** [comment]
Resolved with updating:
```
"@lhci/cli": "^0.9.0",
```
