### ISSUE TITLE
Snap E2E Fail Rate

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#491]
Having inconsistent test results in Cypress causing build tests to fail at times:

**autocomplete.spec.js**
<img width="970" alt="image" src="https://user-images.githubusercontent.com/5060400/167479049-8ee1b0a2-c089-440d-bc93-39fe3e98b7a9.png">

**Comment by chrisFrazier77** [comment]
![F7A498B4-DA90-4C20-8E24-549923CAA8A3_1_105_c](https://user-images.githubusercontent.com/22894994/167737697-039f9edb-f7d2-4e2a-8aa5-13a68985ce0d.jpeg)
This one failed and then passed on re run today too.

**Comment by chrisFrazier77** [comment]
![19273FC8-A7DA-462F-B3C7-88BD6DA70FDE](https://user-images.githubusercontent.com/22894994/168169180-ddb5308b-dd68-4163-8808-978fe3e923a4.jpeg)

**Comment by korgon** [comment]
And another one...
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/5060400/169412539-381b8fb6-00fc-4309-8f9a-d2d2476277f1.png">

**Comment by korgon** [comment]
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/5060400/169413573-569df780-be3f-4d1d-8e19-4fe4757f1fe3.png">

**Comment by korgon** [comment]
Still a problem:


![Image](https://user-images.githubusercontent.com/5060400/171925629-8131cdee-1bf4-4196-9d5d-9429adbbc08f.png)

**Comment by chrisFrazier77** [comment]
![A05BE992-F2BD-4A3D-9C9D-6092BCCD2646_4_5005_c](https://user-images.githubusercontent.com/22894994/172486280-d6c29592-3da0-4a5d-b56e-9a6f52e58b94.jpeg)
Been seeing this one sometimes when running locally

**Comment by korgon** [comment]
@chrisFrazier77 Lame... I just saw this related one...
<img width="808" alt="image" src="https://user-images.githubusercontent.com/5060400/172493368-9fa9ea80-0615-43e6-b427-3327dee3c243.png">

**Comment by korgon** [comment]
Sigh...


![Image](https://user-images.githubusercontent.com/5060400/173376015-8756212c-2e9e-4bca-8583-4bdd8ec0abd7.png)

**Comment by korgon** [comment]
Can't get things passing locally any more - always something failing now.

![Image](https://user-images.githubusercontent.com/5060400/173386203-e5361583-3e8d-4252-a276-575f4c9b8683.png)

**Comment by korgon** [comment]
Infinite fail:


![Image](https://user-images.githubusercontent.com/5060400/179602733-69745fed-05b9-4f79-a34c-47f8845fe14f.png)

**Comment by korgon** [comment]
^ still a problem...

**Comment by korgon** [comment]
Testing has stabilized and no longer presents release blockers - there may be tests that still fail on rare occasions, but should these pop up again in the future we will address them then.
