### ISSUE TITLE
cross-sell profiles missing product param when batched

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#507]
It looks like the batched request is missing `product` sku from the request params when a cross-sell profile is batched, resulting in 0 results for that profile.

Note: Try upgrading the client's Snap version 0.24.0 -> 0.27.0

https://searchspring.slack.com/archives/C028X3E38BB/p1653411353522039

**Comment by korgon** [comment]
Non-issue on v0.27.5. Closing.
