### ISSUE TITLE
Recommendation conditional rendering

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#566]
Some clients using older recommendation (or custom) templates don't have the recent conditional rendering we added. 
```
return store.results.length > 0 && (
    <Recommendation controller={controller}/>
);
```
This task is to ensure that the Recommendation component can be used without ` store.results.length > 0` and not render anything if children or results are empty.

**Comment by chrisFrazier77** [comment]
Seems to work as expected even without the store.results.length > 0. Tested with & without children.
