### ISSUE TITLE
Beacon meta version

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#574]
After our [recent change to the datawarehouse](https://github.com/searchspring/datawarehouse/pull/7) we noticed that the `meta` is not being saved anywhere. This is particularly important to the Snap team because it contains the Snap version that triggered the error event. We need to either modify the core pipeline to track the meta/version with our type='error' events, or add the Snap version to the error event payload (less ideal, duplicated data, but easier/less risk solution)

Side note: Look into why we found some duplicated events in tables (timestamps had the same values)

**Comment by korgon** [comment]
The datawarehouse changes are completed and v0.33.0 of Snap adds logic to prevent sending errors in development and also for mockups.
