### ISSUE TITLE
Send empty query on landing pages

### ISSUE THREAD

**Issue by chrisFrazier77** [searchspring/snap#601]
Glik's reported that they are not seeing facets with landing pages. https://www.gliks.com/collections/shop?tag=stranger-things&fts=0&preview_theme_id=125714530404 When I look at the store controller, I see facets array as empty, but I can see the facets in the meta object and if you compare to this v3 sample, we do show facets in the sidebar. http://a.cdn.searchspring.net/sites/searchspring.lite/pike/index.html?siteId=vyzcgd&tag=stranger-things 

This is due to the missing search query. which is included as an empty string in the v3 example. Snap should automatically handle this and add an empty string as the search query if there is a landing page tag.

**Comment by korgon** [comment]
Would be nice if the API handled this better.

**Comment by korgon** [comment]
There is an open issue on the API side of things for this. We will await that fix instead of patching the issue within Snap.
