### ISSUE TITLE
Default events for Snap

### ISSUE THREAD

**Issue by julesbravo** [searchspring/snap#624]
Is it possible to dispatch certain events by default in Snap whenever results render? We often have customers that need to listen for events to initialize certain functionality and it'd be good if we just had a default event they can listen for.

**Comment by korgon** [comment]
Leaving this to a per-implementation solution for now due to nature of custom components and Snap core being unable to know specifically when these components have rendered.

Perhaps a plugin could be written to help with this repeated request.
