### ISSUE TITLE
Integrated Spell Correction

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#631]
Integrated spell correction changes the way that spell correct is handled. Instead of relying upon the suggest API to do the correction via term suggestions, the search API does the correction itself. We must continue to support the previous method while also making this the default behavior moving forward.

Changes to Search behavior:
1. The API will respond with `query.corrected` and `query.original` when enabled and occured
2. when spell correction occurs add details about the correction to the page: `Hmmm, we couldn't find anything for "shoez", so we searched for "shoes"`

Changes to AC behavior:
1. no longer use first suggestion from suggest API
2. AC is to only search for what is in the input
3. The API will respond with `query.corrected` and `query.original` when enabled and occured
4. when spell correction occurs add details about the correction to the component: `Hmmm, we couldn't find anything for "shoez", so we searched for "shoes"`

---

Since this change crosses several controllers we will likely need to add a new configuration section to snap-preact to handle configuring the controllers.

**Comment by njkuhne** [comment]
I think you may not need the enableSpellCorrect=true in production, @thatDAMNbobby  can you confirm?

**Comment by korgon** [comment]
Confirmed that this will not be needed. We will use the new response from the API to determine if this feature is enabled.

**Comment by korgon** [comment]
From mobbing session:

1. send param in suggest API (Client)
2. modify transform for changing search.query and search.originalQuery to query.corrected and query.original (Client)
3. modify snap adding settings.features.integratedSpellCorrection and toggle client global (#1)
4. modify autocompletecontroller behavior to not set input value and oq param and instead send fallbackQuery (AutocompleteController)
5. modify snap to auto configure autocompletecontroller by apply integratedspellcorrect setting
6. update template with new config and component changes (for "searched instead for...")

**Comment by korgon** [comment]
@chrisFrazier77 @dkonieczek 
Initial branch created: https://github.com/searchspring/snap/tree/integrated-spell-correction

Remaining work:
* add testing to branch work
* add documentation to branch work
* release by merging into develop and then main
* update snapfu-template-preact so that all new sites have the feature enabled
