### ISSUE TITLE
Recommendation Documentation

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#652]
The Snap documentation needs improvement with regards to recommendations and the recommendation instantiator.

New page under Getting Started -> Preact -> Recommendations should be added that discusses instantiator config (adding it to the snap config) and how the profile / templating / component setup works.

**Comment by dkonieczek** [comment]
Also add:
- multiple siteIds in package.json
- snap-action usage
- github secrets requirement for snap-action & multi siteId
