### ISSUE TITLE
Cypress tests failing in action

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#654]
In some cases cypress tests will pass locally but fail when running in the cloud. After some debugging I came across this familiar error:
```
Automatic publicPath is not supported in this browser
```
This occurs when code splitting is enabled and the browser cannot determine the host of where to fetch the chunk files. This can be confirmed by disabling code splitting for bundle.js in webpack.dev.js and then the tests pass in the cloud. 
The root cause seems to be due to using webpack 5 with this version of cypress but we have other sites that are working so something else may be causing this. Creating this issue to further investigate or how we want to handle this. Cypress just a few days ago [released the fix](https://github.com/cypress-io/cypress/pull/23760) to this and it looks like they're disabling code splitting so that may be an option we could consider (just for the modern bundle.js in webpack.dev.js)

Related links with some workarounds I couldn't get to work:
https://github.com/cypress-io/cypress/issues/8900
https://github.com/cypress-io/cypress/issues/18435#issuecomment-972309941

**Comment by korgon** [comment]
First thing to do should be to test updating Cypress on site in question.

**Comment by korgon** [comment]
No longer an issue.
