### ISSUE TITLE
Closing Autocomplete

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#680]
Using the default Autocomplete facets, if we're on a search page with a query applied and select a facet option in Autocomplete, the Autocomplete doesn't close. Clicking on a facet link in Autocomplete should close the Autocomplete window so users know a change has happened. This was fixed in previous versions of our integration, but seems to have popped up in Snap.

It would also be nice to have a function in the Autocomplete controller which we can use to close Autocomplete. This could be placed on custom links or buttons in Autocomplete, like if someone wants a "Close" button for the Autocomplete.

**Comment by chrisFrazier77** [comment]
I cant seem to reproduce this on the demo store, Maybe it only happens on spa sites? 

As for the function in the controller, I believe just calling controller.reset() is what is needed? This closes the component and wipes the input value. 

Additionally, maybe we should call controller.reset() on click of terms and facets in our component? That would definitely handle any odd edge cases that an spa might bring.

**Comment by shrekked** [comment]
Hi @chrisFrazier77, I wanted to give some more context here, I noticed this happening on a few sites as well, which are not SPAs. 

To reproduce, perform a search which takes you to the site's search page. Then, open autocomplete by typing in the same query, but not submitting the search. By default, clicking any filter in this scenario does not close the Autocomplete, unless the search term is also changed.
