### ISSUE TITLE
Add BPK to request params

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#698]
Modify the transforms and snapi types to allow adding the bpk request parameter. Also use this as an opportunity to create the snap-plugin package.

https://searchspring.slack.com/archives/C028X3E38BB/p1671121406742329

**Comment by dkonieczek** [comment]
https://github.com/searchspring/snap-generator-openapi/pull/26

**Comment by korgon** [comment]
This change is no longer needed as the API has no functional BPK parameter.
