### ISSUE TITLE
Carousel Pagination Configuration

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#714]
Currently the `Recommendation` and `Carousel` components take a `pagination` prop that enables the Swiperjs pagination module - this prop should be changed to also accept a Swiperjs pagination configuration.

https://swiperjs.com/swiper-api#pagination

https://github.com/searchspring/snap/blob/v0.39.2/packages/snap-preact-components/src/components/Molecules/Carousel/Carousel.tsx#L300

**Comment by adriamurphy** [comment]
@korgon I was playing around with the ```Navigation``` module in swiper and it looks like it doesn't work for the same reasons as the ```Pagination``` module. Can we get this to work with the ```Navigation``` module as well so have the ability to move the navigation arrows as needed? 

Also I realized that if you put ```prevButton``` and ```nextButton``` props as ```false``` (or even an empty string) the arrows still load. We should be able to opt out of these or not show them at all.
