### ISSUE TITLE
Infinite Scroll "load more" pageSize parameter

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#718]
Not sure what you would call this, but currently infinite scroll will always load the number of results based on the pageSize, both initially and when loading more. I'm requesting that we have a parameter for changing the number of products loaded after the user hits the "load more" point.

**Example:** Initially a customer has 48 products per page, but when hitting the bottom of the results, they only want to load 12 at a time.

**Comment by korgon** [comment]
I'm thinking a `pageSize` option in `infinite` settings for the controller. This could complicate the backfill - but we will evaluate usage.

**Comment by korgon** [comment]
Due to pagination within the API, we cannot support this functionality until some sort of offset is supported API side.
