### ISSUE TITLE
Test Reliability

### ISSUE THREAD

**Issue by chrisFrazier77** [searchspring/snap#745]
Currently there are a handful of "this.skip" lines in the autcomplete cypress test. These are causing inconsistent test outcomes as sometimes a test will fail, and other times it will skip itself and pass. We should not be skipping any of these tests. All the skip tests should be removed, and the testing should be corrected to be more consistent and reliable.

**Comment by korgon** [comment]
Fix was not reliable... Additionally the tracker test is failing - perhaps that could be addressed as well.
