### ISSUE TITLE
facet slider low handle doesn't reset

### ISSUE THREAD

**Issue by chrisFrazier77** [searchspring/snap#774]
When using the facet slider, if you drag the lower handle, and then clear the facet, the url state, and products all update as expected but the slider doesnt re-render and the lower handle stays where you left it. 

Not for some reason this only happens with the lower handle, the upper handle works as expected.

**Comment by chrisFrazier77** [comment]
This seems to have resolved itself. I can no longer reproduce the bug.

**Comment by korgon** [comment]
A reproducible situation has come back up.

**Comment by korgon** [comment]
Released in v0.44.2
