### ISSUE TITLE
Slideout width

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#825]
This is not a big issue, but very low cost to fix. I think the default ```width``` for slideout should be ```100%``` instead of ```90%```.
https://github.com/searchspring/snap/blob/main/packages/snap-preact-components/src/components/Molecules/Slideout/Slideout.tsx#L26

If you want a full width slideout and set the ```width``` prop to ```100%```, that doesn't achieve the effect. I do realize you can do a CSS override, but this seems like a small improvement easily made.

**Comment by korgon** [comment]
I do not think we can change the default here to 100% due to backwards compatibility. However, we could make it properly respect the prop `width` when it passes a value of 100% to also adjust accordingly so that 100% is achievable.
