### ISSUE TITLE
Slideout docs

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#826]
Testing in Chrome on Mac.

If you go to the Slideout section of the docs:
https://searchspring.github.io/snap/#/components-preact

You get a preview of the slideout where the slideout is open. If I switch to the "Docs" tab, I can't scroll to see the props. My guess is this has something to do with the slideout being fixed and overflow styles carrying over to this tab. 

To fix it, I can resize the screen on the "Docs" tab or close the slideout on the "Canvas" tab then go back to "Docs". Is it possible to close the slideout when clicking on the "Docs" tab?

**Comment by korgon** [comment]
Should be easy enough to implement a fix for this. Thanks for bringing it to our attention!
