### ISSUE TITLE
getContext escape special characters

### ISSUE THREAD

**Issue by chrisFrazier77** [searchspring/snap#837]
Currently, the getContext function does not escape special characters such as /, so if your category name has something like that in it, it breaks things and doesn't match and ends up showing 0 results. 

Example - 

<script src="bundle.js" id="searchspring-context">
	category = { id : "129", name : "TEC \ Minneapolis", path : "Brands>TEC \ Minneapolis" };
</script>

**Comment by korgon** [comment]
Not proceeding with this change as the characters are being passed this way and can be modified via scripting.
