### ISSUE TITLE
Storybook Dependancy Error

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#843]
Currently we cannot build snap-preact-components without the current package-lock.json 

Looks like one of storybook's dependancy changed and is causing this error 

![Screenshot 2023-06-21 at 10 33 36 AM](https://github.com/searchspring/snap/assets/13966707/a0b3a035-1b80-4589-9aba-a93b4fb40591)

**Comment by korgon** [comment]
Running a clean install resolves this now - but Select and Button tests break due to button being in an odd hover state.
