### ISSUE TITLE
Badges Container Component

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#987]
Need to explore what a configurable badge overlay component could look like.

The overlay should be flexible enough to support being used in various locations, including as an overlay (position absolute) or as a callout (inline). Each container should have a specific id/name that lines up with the various locations available for badges. Default badge locations are 'left', 'right' and 'callout'; but these can be customized.

Within each container (location) we will want an easy way to handle offsets and positioning of the badge components.

Badge components are a separate but related task that would involve the creation of actual components that would be used for badge display (eg. Pill / Rectange / etc...) that would be used _inside_ of these containers.

**Comment by dkonieczek** [comment]
Automation moved this to done... Snap portion still not merged
