### ISSUE TITLE
Branch Switch doNotTrack

### ISSUE THREAD

**Issue by dkonieczek** [searchspring/snap#996]
The branch preview doesn't work in certain browsers (firefox) that by default set `window.navigator.doNotTrack` and prevent cookies from being set (in featureFlags.ts)
Since the branch switch cookie can't be set, the branch preview doesn't persists across page navigation. 
Perhaps we could fallback to localStorage or consider removing the restriction since the doNotTrack api is deprecated.

**Comment by korgon** [comment]
Restriction was removed in [v0.53.0](https://github.com/searchspring/snap/releases/tag/v0.53.0).
